package com.fortysevendeg.ninecardslauncher.modules

import com.fortysevendeg.macroid.extras.ContextWrapperProvider
import com.fortysevendeg.ninecardslauncher.modules.api.impl.ApiServicesComponentImpl
import com.fortysevendeg.ninecardslauncher.modules.appsmanager.impl.AppManagerServicesComponentImpl
import com.fortysevendeg.ninecardslauncher.modules.googleconnector.impl.GoogleConnectorServicesComponentImpl
import com.fortysevendeg.ninecardslauncher.modules.image.impl.ImageServicesComponentImpl
import com.fortysevendeg.ninecardslauncher.modules.persistent.impl.PersistentServicesComponentImpl
import com.fortysevendeg.ninecardslauncher.modules.repository.impl.RepositoryServicesComponentImpl
import com.fortysevendeg.ninecardslauncher.modules.user.impl.UserServicesComponentImpl

trait ComponentRegistryImpl
  extends ComponentRegistry
  with ContextWrapperProvider
  with ImageServicesComponentImpl
  with AppManagerServicesComponentImpl
  with RepositoryServicesComponentImpl
  with PersistentServicesComponentImpl
  with UserServicesComponentImpl
  with GoogleConnectorServicesComponentImpl
  with ApiServicesComponentImpl

