package com.fortysevendeg.ninecardslauncher.modules

import com.fortysevendeg.ninecardslauncher.commons.ContextWrapperProvider
import com.fortysevendeg.ninecardslauncher.modules.api.impl.ApiServicesComponentImpl
import com.fortysevendeg.ninecardslauncher.modules.appsmanager.impl.AppManagerServicesComponentImpl
import com.fortysevendeg.ninecardslauncher.modules.googleconnector.impl.GoogleConnectorServicesComponentImpl
import com.fortysevendeg.ninecardslauncher.modules.image.impl.ImageServicesComponentImpl
import com.fortysevendeg.ninecardslauncher.modules.persistent.impl.PersistentServicesComponentImpl
import com.fortysevendeg.ninecardslauncher.modules.repository.cacheCategory.CacheCategoryRepositoryServicesComponentImpl
import com.fortysevendeg.ninecardslauncher.modules.repository.card.CardRepositoryServicesComponentImpl
import com.fortysevendeg.ninecardslauncher.modules.repository.collection.CollectionRepositoryServicesComponentImpl
import com.fortysevendeg.ninecardslauncher.modules.repository.geoInfo.GeoInfoRepositoryServicesComponentImpl
import com.fortysevendeg.ninecardslauncher.modules.user.impl.UserServicesComponentImpl

trait ComponentRegistryImpl
  extends ComponentRegistry
  with ContextWrapperProvider
  with ImageServicesComponentImpl
  with AppManagerServicesComponentImpl
  with CacheCategoryRepositoryServicesComponentImpl
  with CardRepositoryServicesComponentImpl
  with CollectionRepositoryServicesComponentImpl
  with GeoInfoRepositoryServicesComponentImpl
  with PersistentServicesComponentImpl
  with UserServicesComponentImpl
  with GoogleConnectorServicesComponentImpl
  with ApiServicesComponentImpl

